import { useState, useEffect } from 'react';

// Initial IoT nodes data
export const INITIAL_NODES = [
  {
    id: 'NODE-01',
    name: 'Nashik Solar Micro-Hub A1',
    location: 'Nashik, MH (20.0059° N, 73.7898° E)',
    crop: 'Nashik Thompson Grapes',
    quantity: '8.5 MT',
    temp: 3.8,
    humidity: 91,
    ethylene: 0.14,
    shelfLifeIndex: 97.4,
    status: 'OPTIMAL',
    gateInVerified: true,
    sensorBattery: 98,
    lastPing: '2s ago',
  },
  {
    id: 'NODE-02',
    name: 'Reefer Transit MH-15-EV',
    location: 'In-Transit -> Mumbai Mandi (19.0760° N, 72.8777° E)',
    crop: 'Ratnagiri Alphonso Mangoes',
    quantity: '12.0 MT',
    temp: 4.2,
    humidity: 88,
    ethylene: 0.22,
    shelfLifeIndex: 94.8,
    status: 'IN_TRANSIT',
    gateInVerified: false,
    sensorBattery: 92,
    lastPing: '1s ago',
  },
  {
    id: 'NODE-03',
    name: 'Azadpur Smart Cold Depot',
    location: 'Delhi NCR (28.7041° N, 77.1025° E)',
    crop: 'Kinnow Oranges (FPO Batch #44)',
    quantity: '22.4 MT',
    temp: 3.5,
    humidity: 93,
    ethylene: 0.09,
    shelfLifeIndex: 98.9,
    status: 'OPTIMAL',
    gateInVerified: true,
    sensorBattery: 100,
    lastPing: '3s ago',
  },
];

export const INITIAL_MCP_LOGS = [
  {
    id: 1,
    timestamp: '11:28:14',
    tool: 'get_mandi_prices',
    args: { commodity: 'Grape', region: 'Mumbai Vashi' },
    result: 'Current Mandi Rate: ₹84/kg. Heat spike alert in Thane bypass (+3.4°C ambient).',
    status: 'SUCCESS',
  },
  {
    id: 2,
    timestamp: '11:28:30',
    tool: 'check_iot_shelf_life',
    args: { nodeId: 'NODE-02', ambientTemp: '38°C' },
    result: 'Freshness decay acceleration +14%/hr on default route. Reroute suggested.',
    status: 'WARNING',
  },
  {
    id: 3,
    timestamp: '11:28:45',
    tool: 'reserve_cold_hub_slot',
    args: { hubId: 'NASHIK-HUB-01', duration: '48h', capacity: '12MT' },
    result: 'Solar Micro-Hub Slot #4 Reserved. IoT Gate-In Smart Lock Code: #AGY-9921',
    status: 'SUCCESS',
  },
];
